# Gitleaks Configuration for CIA App
title = "CIA App Secret Scanner"

[extend]
useDefault = true

# Custom rules voor specifieke patterns
[[rules]]
description = "OpenAI API Key"
id = "openai-api-key"
regex = '''sk-proj-[a-zA-Z0-9]{48}'''
tags = ["key", "openai"]

[[rules]]
description = "Google API Key"
id = "google-api-key"  
regex = '''AIza[0-9A-Za-z\-_]{35}'''
tags = ["key", "google"]